version: 2
before:
  hooks:
    - ./scripts/update_version.sh
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
brews:
  - url_template: "https://github.com/gerdou/tfbox/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: gerdou-app[bot]
      email: 2530509+gerdou-app[bot]@users.noreply.github.com
    homepage: "https://github.com/gerdou/tfbox"
    description: "Another terraform version selector, combined with docker"
    license: "MIT"
    test: system "#{bin}/tfbox --version"
    install: bin.install "tfbox"
    repository:
      owner: gerdou
      name: homebrew-tfbox
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
